export { default as Navigation } from "../components/Navigation";
export { default as Footer } from "./Footer";
export { default as Hero } from './Hero';
export { default as Expertise } from "./Expertise";
export { default as Timeline } from "./Timeline";
export { default as Project } from "./Project";
export { default as Contact } from "./Contact";
export { default as About } from './About';
export { default as Education } from './Education';
